name: omega_evaluation_project
description: Evaluation project for omega
authors:
  - ali mohammadi <alimohammadi7117@gmail.com>
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^0.5.3
  json_annotation: ^3.0.1
  url_launcher: ^5.4.1
  package_info: ^0.4.0+13
  provider: ^4.0.1
  rxdart: ^0.22.0
  intl: ^0.16.0
  retrofit: ^1.0.1+1
  flutter_local_notifications: ^1.4.0
  android_alarm_manager: ^0.4.5+8
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.8.1
  json_serializable: ^3.2.5
  retrofit_generator: ^1.0.2+2


flutter:
  uses-material-design: true
  fonts:
    - family: IranNastaliq
      fonts:
        - asset: res/assets/fonts/iran_nastaliq.ttf
    - family: Iran
      fonts:
        - asset: res/assets/fonts/iran_sans.ttf
          weight: 400

